{% set name = "parmap" %}
{% set version = "1.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 375f12ad4844726647a2b7b1a522201ea38e1f9a092527d2f5ba2cf62d709347

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - parmap

about:
  home: http://github.com/zeehio/parmap
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: 'map and starmap implementations passing additional arguments and parallelizing if possible'
  description: |
    parmap is a simple package that provides map and parmap implementations, passing
    additional arguments and managing the multiprocessing pools if desired.
  doc_url: https://parmap.readthedocs.io/
  dev_url: https://github.com/zeehio/parmap

extra:
  recipe-maintainers:
    - zeehio
