{% set name = "parmap" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 77c45210617c3c084e073d61e3a8111e398bbc606d4e3ec03f9a0c3aadc3f47b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7

test:
  imports:
    - parmap

about:
  home: http://github.com/zeehio/parmap
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: 'map and starmap implementations passing additional arguments and parallelizing if possible'
  description: |
    parmap is a simple package that provides map and parmap implementations, passing
    additional arguments and managing the multiprocessing pools if desired.
  doc_url: https://parmap.readthedocs.io/
  dev_url: https://github.com/zeehio/parmap

extra:
  recipe-maintainers:
    - zeehio
