travis:
  secure:
    BINSTAR_TOKEN: GatzOE6XRAqVuLe4J48S/+NOmK32/0IQQYTodCI/QLucXxFwHuK5BusUJyfnotLB+C+grPeCMMTGnuf3fBCPAsHX1fH80VGRvKT0DAXYo6t74pwKu4vNbH0Ns4X9O8+mY32C6IWcxn83uOLGtPphkum6HJneWMXeFIjWEuuhxZPMJLw9oZ8u52EAAbKQPPYR7vDytgbVjYEFgZpm5TGSCIi8jeC0f4rVeJTF/nIl7BXq8ymfRnqEz1cew8K7M4coy0dYRCvzdV+xsCCh29j5HnKh6n+N118sPBFBGF9lSH+iI6ubyMtVwCPC70iGpeboY2IOJW36KJna72fiLZtRu0SnTBX84fT4nMK7DeESAnh4qP+4L9tuKcqOlzuVtUyKsMJgdNUxJHs+fWEkYInl/J5GpAXZIUtIw8eff4uNzquZ6xi7ebsjfeI+gBBgX8kowN9KW6CiVLKfRs9BxgbdwrdkoDq8KTMqaxh+YYBEWZYNk7zBctWZ7oVwke1jp8sjPf0VYxPIwhSkINofsfOBivHFxtQ6V8AatV0JJKwULbUr3ZGv8jv1uDn1hmfT8VLLWSXJ5T6atYpYJfZg3pvfTImER5y2alKSPvT0RyGzM2eDko2vXhtJjfY+6yERvmkOv4jhhUoQxG3aumOZ/so1ycLwh5n9Am9p1h2PmzMtVWs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
